name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    name: Test Backend (.NET)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: |
          cd api
          dotnet restore Ecommerce.sln

      - name: Build
        run: |
          cd api
          dotnet build Ecommerce.sln --no-restore --configuration Release

      - name: Run tests
        run: |
          cd api
          dotnet test Ecommerce.sln --no-build --configuration Release --verbosity normal

  test-frontend:
    name: Test Frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd web
          npm install

      - name: Run ESLint
        run: |
          cd web
          npm run lint

      - name: Run tests
        run: |
          cd web
          npm run test

      - name: Build
        run: |
          cd web
          npm run build

  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check .NET code formatting
        continue-on-error: true
        run: |
          cd api
          dotnet format --verify-no-changes --verbosity diagnostic || echo "Code formatting issues found"

      - name: Install frontend dependencies
        run: |
          cd web
          npm install

      - name: Check frontend code quality
        run: |
          cd web
          npm run lint
